version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3308:3306"
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin08
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_ROOT_USER}
      PMA_PORT: ${MYSQL_ROOT_PORT}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network
  ubuntu81:
    build: .
    container_name: ubuntu_php81
    tty: true
    stdin_open: true
    ports:
      - "81:80"
    volumes:
      - ${FOLDER_DESTINATION}:/var/www
    depends_on:
      - mysql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge