version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'ar7711'
    ports:
      - '3308:3306'
    volumes:
      - ./../sql/create_user.sql:/docker-entrypoint-initdb.d/create_user.sql
      - ./../sql/alter_user.sql:/docker-entrypoint-initdb.d/alter_user.sql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin08
    environment:
      PMA_HOST: mysql
      PMA_USER: 'root'
      PMA_PORT: '3306'
      PMA_PASSWORD: 'ar7711'
    ports:
      - "0808:80"
    depends_on:
      - mysql
    networks:
      - app-network
  ubuntu81:
    build: .
    container_name: ubuntu_php81
    tty: true
    stdin_open: true
    ports:
      - "81:80"
    volumes:
      - ./../src:/var/www
      - ./../.ssh:/root/.ssh
    depends_on:
      - mysql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
