services:
  mysql56:
    image: mysql:5.6
    container_name: mysql56
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3356:3306"
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin56
    environment:
      PMA_HOST: mysql56
      PMA_USER: ${MYSQL_ROOT_USER}
      PMA_PORT: ${MYSQL_ROOT_PORT}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "5656:80"
    depends_on:
      - mysql56
    networks:
      - app-network
  ubuntu73:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: ubuntu_php73
    tty: true
    stdin_open: true
    ports:
      - "73:80"
    volumes:
      - ${FOLDER_DESTINATION}:/var/www
    depends_on:
      - mysql56
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
